variable "env" {
  description = "Environment short name."
  type        = string

  validation {
    condition     = contains(["dev", "tst", "prd"], var.env)
    error_message = "env must be one of: dev, tst, prd."
  }
}

variable "database_raw" {
  description = "Name of the raw/landing database."
  type        = string
}

variable "database_analytics" {
  description = "Name of the dbt-managed database."
  type        = string
}

variable "database_ops" {
  description = "Name of the platform operations database."
  type        = string
}

variable "schema_raw" {
  description = "Schema in the raw database holding seeded source data."
  type        = string
  default     = "JAFFLE_RAW"
}

variable "schema_staging" {
  description = "Schema holding dbt staging models."
  type        = string
  default     = "JAFFLE_STG"
}

variable "schema_marts" {
  description = "Schema holding dbt mart models."
  type        = string
  default     = "JAFFLE_MARTS"
}

variable "schema_dbt_projects" {
  description = "Schema in the ops database holding DBT PROJECT objects."
  type        = string
  default     = "DBT_PROJECTS"
}

variable "warehouse_transform" {
  description = "Warehouse granted to TRANSFORMER and LOADER."
  type        = string
}

variable "warehouse_reporting" {
  description = "Warehouse granted to ANALYST."
  type        = string
}

variable "dbt_service_user_public_key" {
  description = <<-EOT
    RSA public key for SVC_DBT, single line, without PEM header and trailer.
    Generated by bootstrap/generate_keypair.sh. This is a public key, so it is
    safe to hold in a tfvars file or a non-sensitive HCP variable; the matching
    private key belongs in the dbt repository's GitHub Actions secrets.
  EOT
  type        = string
}

variable "allow_developer_schemas" {
  description = <<-EOT
    When true, TRANSFORMER may create and own schemas in the analytics database.
    This is what lets each engineer build into ANALYTICS.DBT_<USER> and lets CI
    create ephemeral ANALYTICS.PR_<n> schemas without a Terraform change.
    Intended for the development account only.
  EOT
  type        = bool
  default     = false
}
